version: '3'

services:
  server:
    build: .
    ports:
      - 8080:8080
    container_name: sample_server
    volumes:
      - .:/go
    tty: true
    restart: always
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    image: mysql:5.7
    container_name: sample_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
